version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: SportAssistantBackend
    volumes:
      - ./app:/backend/app
      - ./scripts/start.sh:/start.sh
      - ./alembic:/backend/alembic
      - ./alembic.ini:/backend/alembic.ini
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: 
      - /bin/sh
      - -c
      - |
        chmod +x /start.sh && /start.sh
    depends_on: 
      - db
      - redis
  db:
    image: postgres:14.6-alpine
    container_name: db
    hostname: db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
  redis:
    image:
      redis
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_USER=redis
    ports:
      - 6379:6379
volumes:
  db-data:
