"""COMMENT

Revision ID: 1c276842d256
Revises: e578add6b941
Create Date: 2025-03-03 19:57:39.747224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c276842d256'
down_revision: Union[str, None] = 'e578add6b941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_competition', sa.Column('name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_competition', 'name')
    # ### end Alembic commands ###
