"""edit user model defaults 3

Revision ID: 25e9c358cee8
Revises: f54ccaccd8c3
Create Date: 2025-03-27 14:54:18.604799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e9c358cee8'
down_revision: Union[str, None] = 'f54ccaccd8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
