"""COMMENT

Revision ID: 7915758c1473
Revises: d6185af7b212
Create Date: 2025-02-21 09:26:35.743319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7915758c1473'
down_revision: Union[str, None] = 'd6185af7b212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_competition_day', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_competition_day', 'date')
    # ### end Alembic commands ###
