"""COMMENT

Revision ID: b18a3f66c5ec
Revises: 4a62d6524458
Create Date: 2025-02-21 22:40:00.892775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18a3f66c5ec'
down_revision: Union[str, None] = '4a62d6524458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_competition', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tbl_competition', 'tbl_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_competition', type_='foreignkey')
    op.drop_column('tbl_competition', 'user_id')
    # ### end Alembic commands ###
