"""edit user model defaults

Revision ID: bab9d65133b1
Revises: 5742c125c785
Create Date: 2025-03-26 17:24:45.037406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab9d65133b1'
down_revision: Union[str, None] = '5742c125c785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user', sa.Column('is_info_filled', sa.Boolean(), nullable=True))
    op.alter_column('tbl_user', 'coach_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_user', 'coach_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tbl_user', 'is_info_filled')
    # ### end Alembic commands ###
