"""COMMENT

Revision ID: d6185af7b212
Revises: 88204fd6cb78
Create Date: 2025-02-21 09:16:22.536958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6185af7b212'
down_revision: Union[str, None] = '88204fd6cb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tbl_competition', ['id'])
    op.drop_column('tbl_competition', 'results')
    op.create_unique_constraint(None, 'tbl_competition_day', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_competition_day', type_='unique')
    op.add_column('tbl_competition', sa.Column('results', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tbl_competition', type_='unique')
    # ### end Alembic commands ###
