"""Add comprehensive and med examinations  models

Revision ID: d71754056912
Revises: 8d382e45145e
Create Date: 2025-03-16 17:50:59.186743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71754056912'
down_revision: Union[str, None] = '8d382e45145e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_comprehensive_examination',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('institution', sa.Text(), nullable=False),
    sa.Column('specialists', sa.Text(), nullable=False),
    sa.Column('methods', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('institution'),
    sa.UniqueConstraint('methods'),
    sa.UniqueConstraint('recommendations'),
    sa.UniqueConstraint('specialists')
    )
    op.create_table('tbl_med_examination',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('institution', sa.Text(), nullable=False),
    sa.Column('methods', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('institution'),
    sa.UniqueConstraint('methods'),
    sa.UniqueConstraint('recommendations')
    )
    op.create_unique_constraint(None, 'tbl_note', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_note', type_='unique')
    op.drop_table('tbl_med_examination')
    op.drop_table('tbl_comprehensive_examination')
    # ### end Alembic commands ###
